name: Run Tests

on:
  push:
    branches:
      - main  # Change to your branch name if needed
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.5'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy pandas scikit-learn
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi  # Handles missing requirements.txt

      - name: Run test script
        run: distance_classification.py  # Ensure file exists!
